version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 healthrecords.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .local.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .local.env

volumes:
  postgres_data: 