# Generated by Django 5.2.1 on 2025-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text="Doctor's specialization (e.g., Cardiology, Pediatrics)", max_length=100, null=True),
        ),
    ]
