# Generated by Django 5.2.1 on 2025-05-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='record_id',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
